<a href="https://colab.research.google.com/github/vermarj/MILEAGE-PREDICTION/blob/main/Internship_project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **MILEAGE PREDICTION - REGRESSION ANALYSIS**

## **Objectives**

         The objective of mileage prediction in machine learning is to build a model that can accurately estimate the fuel efficiency or mileage of a vehicle based on various input features.

## **Data Source**

      The Origin Of This Data Is From The StatLib Library Which Is Maintained At Camegie Mellon University. The Dataset Used In The 1983 American Statistical Association Expositon. In This Program This Data Is Taken From The Github Platfrom From The YBI Foundation. The Data Is A "CSV" File Type.

## **Import Library**

In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
import matplotlib.pyplot as pllt

In [4]:
import seaborn as sns

## **Import Data**

In [5]:
df=pd.read_csv('https://github.com/YBIFoundation/Dataset/raw/main/MPG.csv')

In [6]:
df.head()

mpg  cylinders  displacement  horsepower  weight  acceleration  \
0  18.0          8         307.0       130.0    3504          12.0   
1  15.0          8         350.0       165.0    3693          11.5   
2  18.0          8         318.0       150.0    3436          11.0   
3  16.0          8         304.0       150.0    3433          12.0   
4  17.0          8         302.0       140.0    3449          10.5   

   model_year origin                       name  
0          70    usa  chevrolet chevelle malibu  
1          70    usa          buick skylark 320  
2          70    usa         plymouth satellite  
3          70    usa              amc rebel sst  
4          70    usa                ford torino

## **Describe Data**

In [7]:
df.describe()

mpg   cylinders  displacement  horsepower       weight  \
count  398.000000  398.000000    398.000000  392.000000   398.000000   
mean    23.514573    5.454774    193.425879  104.469388  2970.424623   
std      7.815984    1.701004    104.269838   38.491160   846.841774   
min      9.000000    3.000000     68.000000   46.000000  1613.000000   
25%     17.500000    4.000000    104.250000   75.000000  2223.750000   
50%     23.000000    4.000000    148.500000   93.500000  2803.500000   
75%     29.000000    8.000000    262.000000  126.000000  3608.000000   
max     46.600000    8.000000    455.000000  230.000000  5140.000000   

       acceleration  model_year  
count    398.000000  398.000000  
mean      15.568090   76.010050  
std        2.757689    3.697627  
min        8.000000   70.000000  
25%       13.825000   73.000000  
50%       15.500000   76.000000  
75%       17.175000   79.000000  
max       24.800000   82.000000

In [8]:
df.info

<bound method DataFrame.info of       mpg  cylinders  displacement  horsepower  weight  acceleration  \
0    18.0          8         307.0       130.0    3504          12.0   
1    15.0          8         350.0       165.0    3693          11.5   
2    18.0          8         318.0       150.0    3436          11.0   
3    16.0          8         304.0       150.0    3433          12.0   
4    17.0          8         302.0       140.0    3449          10.5   
..    ...        ...           ...         ...     ...           ...   
393  27.0          4         140.0        86.0    2790          15.6   
394  44.0          4          97.0        52.0    2130          24.6   
395  32.0          4         135.0        84.0    2295          11.6   
396  28.0          4         120.0        79.0    2625          18.6   
397  31.0          4         119.0        82.0    2720          19.4   

     model_year  origin                       name  
0            70     usa  chevrolet chevelle malibu

## **Data Preprocessing**

In [9]:
df.columns

Index(['mpg', 'cylinders', 'displacement', 'horsepower', 'weight',
       'acceleration', 'model_year', 'origin', 'name'],
      dtype='object')

In [10]:
df=df.dropna()

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 392 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   mpg           392 non-null    float64
 1   cylinders     392 non-null    int64  
 2   displacement  392 non-null    float64
 3   horsepower    392 non-null    float64
 4   weight        392 non-null    int64  
 5   acceleration  392 non-null    float64
 6   model_year    392 non-null    int64  
 7   origin        392 non-null    object 
 8   name          392 non-null    object 
dtypes: float64(4), int64(3), object(2)
memory usage: 30.6+ KB


## **Define Target Variable (y) and Feature Variables (X)**

In [12]:
df.columns

Index(['mpg', 'cylinders', 'displacement', 'horsepower', 'weight',
       'acceleration', 'model_year', 'origin', 'name'],
      dtype='object')

In [13]:
y=df['mpg']

In [14]:
y.shape

(392,)

In [15]:
X=df[['displacement', 'horsepower', 'weight',
       'acceleration']]

In [16]:
X.shape

(392, 4)

In [17]:
X

displacement  horsepower  weight  acceleration
0           307.0       130.0    3504          12.0
1           350.0       165.0    3693          11.5
2           318.0       150.0    3436          11.0
3           304.0       150.0    3433          12.0
4           302.0       140.0    3449          10.5
..            ...         ...     ...           ...
393         140.0        86.0    2790          15.6
394          97.0        52.0    2130          24.6
395         135.0        84.0    2295          11.6
396         120.0        79.0    2625          18.6
397         119.0        82.0    2720          19.4

[392 rows x 4 columns]

In [18]:
from sklearn.preprocessing import StandardScaler

In [19]:
ss=StandardScaler()

In [20]:
X=ss.fit_transform(X)

In [21]:
X

array([[ 1.07728956,  0.66413273,  0.62054034, -1.285258  ],
       [ 1.48873169,  1.57459447,  0.84333403, -1.46672362],
       [ 1.1825422 ,  1.18439658,  0.54038176, -1.64818924],
       ...,
       [-0.56847897, -0.53247413, -0.80463202, -1.4304305 ],
       [-0.7120053 , -0.66254009, -0.41562716,  1.11008813],
       [-0.72157372, -0.58450051, -0.30364091,  1.40043312]])

In [22]:
pd.DataFrame(X).describe()

0             1             2             3
count  3.920000e+02  3.920000e+02  3.920000e+02  3.920000e+02
mean  -7.250436e-17 -1.812609e-16 -1.812609e-17  4.350262e-16
std    1.001278e+00  1.001278e+00  1.001278e+00  1.001278e+00
min   -1.209563e+00 -1.520975e+00 -1.608575e+00 -2.736983e+00
25%   -8.555316e-01 -7.665929e-01 -8.868535e-01 -6.410551e-01
50%   -4.153842e-01 -2.853488e-01 -2.052109e-01 -1.499869e-02
75%    7.782764e-01  5.600800e-01  7.510927e-01  5.384714e-01
max    2.493416e+00  3.265452e+00  2.549061e+00  3.360262e+00

## **Train Test Split Modeling**

In [23]:
from sklearn.model_selection import train_test_split

In [24]:
X_train,X_test,y_train,y_test=train_test_split(X,y,train_size=0.7,random_state=2529)

In [25]:
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((274, 4), (118, 4), (274,), (118,))

## **Model Evaluation**

In [26]:
from sklearn.linear_model import LinearRegression

In [27]:
model=LinearRegression()

In [28]:
model.fit(X_train,y_train)

LinearRegression()

In [29]:
model.intercept_

23.485738559737584

In [30]:
model.coef_

array([-1.05767743, -1.68734727, -4.10787617, -0.11495177])

In [31]:
from sklearn.preprocessing import PolynomialFeatures

In [32]:
poly=PolynomialFeatures(degree=2,interaction_only=True,include_bias=False)

In [33]:
X_train2=poly.fit_transform(X_train)

In [34]:
X_test2=poly.fit_transform(X_test)

In [35]:
model.fit(X_train2,y_train)

LinearRegression()

In [36]:
model.intercept_

21.27336450063766

In [37]:
model.coef_

array([-2.76070596, -5.00559628, -1.36884133, -0.81225214,  1.24596571,
       -0.12475017, -0.90542822,  1.35064048, -0.17337823,  1.41680398])

In [38]:
y_pred_poly=model.predict(X_test2)

## **Prediction**

In [39]:
from sklearn.metrics import mean_absolute_error,mean_absolute_percentage_error,r2_score

In [40]:
mean_absolute_error(y_test,y_pred_poly)

2.7887147720295977

In [41]:
mean_absolute_percentage_error(y_test,y_pred_poly)

0.12074018342938687

In [42]:
r2_score(y_test,y_pred_poly)

0.7461731314563803

## **Explaination**

          In Mileage prediction project a csv file of MPG is used as a data source to train and predict the model. The libraries are imported (Pandas,Numpy) , and a csv file of MPG is imported. Then data preprocessing were done and dependent variable and independent variables were defined. After that from the variables the Datum were splited as train and test from the library using "sklearn". Then the model is selected and the model is trained with the train Datum. In last step the model is used to predict from the test Datum and the model is evaluated.